#port config
server.port = 8080
server.servlet.context-path= /employee/spring/app/v1


spring.profiles.active= local

#H2 database config
spring.datasource.url=jdbc:postgresql://localhost:5433/employeeDB
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=oblivion
spring.jpa.hibernate.ddl-auto= update

spring.graphql.graphiql.enabled=true

server.error.include-stacktrace=never
reqres.api.url=https://reqres.in/api/users?page=2